### ISSUE TITLE
mainItems 的内容可否异步增删

### ISSUE THREAD

**Issue by WankkoRee** [577fkj/blockmiui#7]
有一个需要显示所有用户应用的`fragment`，希望先显示一个加载中的动画，然后异步添加完所有用户应用的`AuthorV`之后再删除动画或取消显示动画，这个需求可以实现吗？

**Comment by 577fkj** [comment]
后续我会尝试在newapi分支尝试实现

**Comment by 577fkj** [comment]
已实现
